import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../Components/Providers";

export const metadata: Metadata = {
  title: "CodeClimb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#d4c9c9] text-black font-[Knewave]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
